[package]
name = "slatedb_hang_write_pressure_repro"
version = "0.1.0"
edition = "2024"

[dependencies]
slatedb = { path = "../slatedb/slatedb" }
tokio = { version = "1.45.1", features = ["full"] }
rand = "0.9.1"
object_store = "0.12.1"
tracing-subscriber = "0.3.19"
